version: "3.9"
services:
  rabbitmq-service:
    image: rabbitmq:management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - banking-net
    restart: always
  mongodb-service:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb-service
    networks:
      - banking-net
  mysql-service:
    image: mysql:latest
    ports:
        - "3307:3307"
    container_name: mysql-service
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
        - banking-net


  auth-service:
    container_name: auth-service
    build: ./AuthenticationService
    networks:
        - banking-net
    ports:
        - "8081:8081"
    depends_on:
        - mysql-service
    restart: always

  bank-service:
    container_name: bank-service
    build: ./BankService
    networks:
      - banking-net
    ports:
      - "8082:8082"
    depends_on:
      - mongodb-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-service
    restart: always

  transaction-service:
    container_name: transaction-service
    build: ./TransactionService
    networks:
      - banking-net
    ports:
      - "8083:8083"
    depends_on:
      - mongodb-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-service
    restart: always

networks:
  banking-net:
      driver: bridge