apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  labels:
  app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication
        image: ndgsindhu/authentication:20
        ports:
        - containerPort: 8081
        env:
        - name: DB_URL
          value: "mysql://mysql-service:3306/BankDb"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP

