FROM openjdk
WORKDIR usr/lib
ADD ./target/AuthenticationService-0.0.1-SNAPSHOT.jar /usr/lib/AuthenticationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","AuthenticationService-0.0.1-SNAPSHOT.jar"]